name: Cypress cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install command: yarn install
          browser: electron
          record: true
          group: UI Electron 
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ad360ece-4623-457a-9bf8-0b5a9bc2671d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107   
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install command: yarn install
          browser: chrome 
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ad360ece-4623-457a-9bf8-0b5a9bc2671d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
  cypress-firefox-tests:
    needs: cypress-chrome-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install command: yarn install
          browser: firefox
          record: true
          group: UI Firefox 
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ad360ece-4623-457a-9bf8-0b5a9bc2671d
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
