name: Cypress cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install command: yarn install
          browser: electron
          record: true
          group: UI Electron 
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: a5ac536-10c7-4ef6-89f3-a62cad78ca6b
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
